version: "3.6"

services:
  web:
    image: dabbertorres/web-server-base:latest
    depends_on:
      - db
      - mail
    ports:
      - "80:80"
      - "443:443"
    configs:
      - source: web-srv-config
        target: /web.conf
    networks:
      - webnet
    secrets:
      - web-srv-db-password
    volumes:
      - type: volume
        source: certs
        target: /certs
      - type: volume
        source: sessions
        target: /sessions
  db:
    image: dabbertorres/web-server-db:latest
    environment:
      - MYSQL_DATABASE=web
      - MYSQL_ROOT_PASSWORD_FILE=/run/secrets/db-password
    networks:
      - webnet
    secrets:
      - web-srv-db-password
    volumes:
      - type: volume
        source: db-data
        target: /var/lib/mysql
  mail:
    image: dabbertorres/email-send-srv:latest
    configs:
      - source: web-srv-mail-config
        target: /mail.conf
    networks:
      - webnet
    volumes:
      - type: volume
        source: certs
        target: /certs

configs:
  web-srv-config:
    external: true
  web-srv-mail-config:
    external: true

networks:
  webnet:

secrets:
  web-srv-db-password:
    external: true

volumes:
  db-data:
  sessions:
  certs:
