version: "3.6"

services:
  web:
    image: dabbertorres/web-server-base:latest
    depends_on:
      - db
      - mail
      - sessions
    ports:
      - "80:80"
      - "443:443"
    configs:
      - source: web-config
        target: /web.conf
    networks:
      - webnet
    secrets:
      - db-password
      - redis-password
    volumes:
      - type: volume
        source: certs
        target: /certs
  db:
    image: dabbertorres/web-server-db:latest
    environment:
      - MYSQL_DATABASE=web
      - MYSQL_ROOT_PASSWORD_FILE=/run/secrets/db-password
    networks:
      - webnet
    secrets:
      - db-password
    volumes:
      - type: volume
        source: db-data
        target: /var/lib/mysql
  mail:
    image: dabbertorres/email-send-srv:latest
    configs:
      - source: mail-config
        target: /mail.conf
    networks:
      - webnet
    volumes:
      - type: volume
        source: certs
        target: /certs
  sessions:
    image: redis:4.0-alpine
    command: sh -c "redis-server --requirepass `cat /run/secrets/redis-password`"
    networks:
      - webnet
    secrets:
      - redis-password

configs:
  web-config:
    external: true
  mail-config:
    external: true

networks:
  webnet:

secrets:
  db-password:
    external: true
  redis-password:
    external: true

volumes:
  db-data:
  certs:
